SOAPUIOS-375 Fix progress bar update in parallel mode
SmartBear/soapui pull request #367
Opened 2019-01-22 04:04 UTC by DmitryNAleshin

https://smartbear.atlassian.net/browse/SOAPUIOS-375

2019-01-22 06:11 UTC, Alexander-Sviridov requested changes

2019-01-22 06:11 UTC, Alexander-Sviridov commented on soapui/src/main/java/com/eviware/soapui/impl/wsdl/panels/project/WsdlProjectTestSuitesTabPanel.java
> +                    System.out.println("setting coutn to " + String.valueOf(finishCount.get()));
We need to remove ``System.out.println``.

2019-01-22 06:13 UTC, Alexander-Sviridov approved these changes

2019-01-22 06:13 UTC, merged

2019-03-04 19:48 UTC, jpraet commented
I think this caused a bug in SoapUI 5.5: https://community.smartbear.com/t5/SoapUI-Open-Source/SoapUI-5-5-0-will-not-run-project-or-suites-Toolkit-not/td-p/179525

Platform.runLater throws "java.lang.IllegalStateException: Toolkit not initialized".

2019-03-05 05:56 UTC, DmitryNAleshin commented
Not reproduced for me ![image](https://user-images.githubusercontent.com/7437608/53783817-41fd4280-3f24-11e9-8041-0e546082c3c2.png)

2019-03-05 18:42 UTC, jpraet commented
It fails for me if I disable showing the Endpoint explorer and the startup page.