SOAPUIOS-375 Incorrect progress bar and status of run button after parallel run
SmartBear/soapui pull request #388
Opened 2019-01-24 14:35 UTC by AlexanderNikitin-Smartbear

https://smartbear.atlassian.net/browse/SOAPUIOS-375

2019-01-25 09:25 UTC, DmitryNAleshin requested changes
We need to work the same way for sets

2019-01-25 09:25 UTC, DmitryNAleshin commented on soapui/src/main/java/com/eviware/soapui/impl/wsdl/testcase/WsdlProjectRunner.java
> +    private Set<TestSuiteRunner> startedRunners = new HashSet<>();
Why is it different from finishedRunners  way?

2019-01-25 09:30 UTC, AlexanderNikitin-Smartbear commented on soapui/src/main/java/com/eviware/soapui/impl/wsdl/testcase/WsdlProjectRunner.java
> +    private Set<TestSuiteRunner> startedRunners = new HashSet<>();
I keep `finishedRunners` for backward compatibility because it's used in `getResults()` method. But I've synchronize it.

`startedRunners` is protected by `lock` object defined below. It needs for consistency state of `startedRunners` between `onCancel()` and `runParallel()`

2019-01-25 09:31 UTC, AlexanderNikitin-Smartbear commented on soapui/src/main/java/com/eviware/soapui/impl/wsdl/testcase/WsdlProjectRunner.java
> +    private Set<TestSuiteRunner> startedRunners = new HashSet<>();
Also between `onFail()`

2019-01-25 09:34 UTC, DmitryNAleshin commented on soapui/src/main/java/com/eviware/soapui/impl/wsdl/testcase/WsdlProjectRunner.java
> +    private Set<TestSuiteRunner> startedRunners = new HashSet<>();
I disagree with different way of set using.

2019-01-28 07:12 UTC, AlexanderNikitin-Smartbear commented on soapui/src/main/java/com/eviware/soapui/impl/wsdl/testcase/WsdlProjectRunner.java
> +    private Set<TestSuiteRunner> startedRunners = new HashSet<>();
@DmitryNAleshin , Why do disagree?

2019-01-28 07:15 UTC, DmitryNAleshin commented on soapui/src/main/java/com/eviware/soapui/impl/wsdl/testcase/WsdlProjectRunner.java
> +    private Set<TestSuiteRunner> startedRunners = new HashSet<>();
We need to use the same way of usage. Two different ways means that one of the way is incorrect for me.

2019-01-28 07:21 UTC, AlexanderNikitin-Smartbear commented on soapui/src/main/java/com/eviware/soapui/impl/wsdl/testcase/WsdlProjectRunner.java
> +    private Set<TestSuiteRunner> startedRunners = new HashSet<>();
In the end we need to guarantee consistency of the data. For `finishedRunners` just synchronizing is enough, but for `startedRunners` it is not, so I use the external `lock` object.

2022-01-27 15:29 UTC, AlexanderNikitin-Smartbear commented
Outdated

2022-01-27 15:29 UTC, closed without merging