SOAPUIOS-608 Swagger in soap
SmartBear/soapui pull request #697
Opened 2021-12-27 14:16 UTC by AlexanderNikitin-Smartbear

https://smartbear.atlassian.net/browse/SOAPUIOS-608

2021-12-27 14:33 UTC, Alexander-Paeshin commented on soapui/src/main/java/com/smartbear/swagger/Swagger2Importer.java
> +                            ExampleBuilder.fromModel(null, bodyParameterModel, swagger.getDefinitions(), new HashSet<String>());
The example builder shouldn't be used in SoapUI OS

2021-12-27 14:56 UTC, Alexander-Paeshin commented on soapui/src/main/java/com/smartbear/swagger/utils/OpenAPIUtils.java
> +    public static String extractStringFromExampleObject(String contentType, Object example) {
This is also part of preparing sample for request and, as I see, it is not used anywhere.

2021-12-27 15:05 UTC, AlexanderYeremeyev requested changes

2021-12-27 15:05 UTC, AlexanderYeremeyev commented on soapui/src/main/java/com/eviware/soapui/impl/support/MediaTypeUtils.java
> +public class MediaTypeUtils {
first question was about javadoc.
But it is a copy of existing code that is why it is possible implementation.
But absolutely unclear :(

2021-12-27 15:05 UTC, AlexanderYeremeyev commented on soapui/src/main/java/com/smartbear/swagger/ExportSwaggerAction.java
> +    private static final String OPEN_API_3_0 = "OpenAPI 3.0";
as i remember we decided to skip it.

2021-12-27 15:05 UTC, AlexanderYeremeyev commented on soapui/src/main/java/com/smartbear/swagger/ExportSwaggerAction.java
> +                Analytics.trackAction("ExportSwagger",
👍

2021-12-27 15:05 UTC, AlexanderYeremeyev commented on soapui/src/main/java/com/smartbear/swagger/SwaggerImporter.java
> +    String AUTHORIZATION_HEADER = "Authorization";
not the best idea to store constant inside the interface.

2021-12-27 15:05 UTC, AlexanderYeremeyev commented on pom.xml
> +        <io.swagger.core.v3.swagger-models.version>2.1.7</io.swagger.core.v3.swagger-models.version>
can we remove these empty values?

2021-12-28 06:58 UTC, AlexanderYeremeyev commented on soapui/src/main/java/com/smartbear/swagger/ExportSwaggerAction.java
> +                if(exporter == null) {
🥇

2021-12-28 06:58 UTC, AlexanderYeremeyev commented on soapui/src/main/java/com/smartbear/swagger/ExportSwaggerAction.java
> +                    UISupport.showInfoMessage(messages.get("ExportSwaggerAction.InfoMessage.NothingCreated"));
bundles

2021-12-28 10:04 UTC, AlexanderYeremeyev approved these changes
Export will work.
Exactly for me import doesn't work. But @Alexander-Paeshin said that it work for him.
Approve this PR.

2021-12-28 10:40 UTC, AlexanderNikitin-Smartbear commented on soapui/src/main/java/com/eviware/soapui/impl/support/MediaTypeUtils.java
> +public class MediaTypeUtils {
1. Copied from ReadyAPI. There is no javadoc initially.
2. What kind of javadoc you want to the MediaTypeUtils class? Are you sure that common description for the class like "Some utility methods" says to anybody more than class name?

2021-12-28 10:44 UTC, AlexanderNikitin-Smartbear commented on soapui/src/main/java/com/smartbear/swagger/SwaggerImporter.java
> +    String AUTHORIZATION_HEADER = "Authorization";
Initially the field was in the AbstactSwaggerImporter wich is not needed.

2021-12-28 10:59 UTC, merged